SELECT TRANSACTION_TYPE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, BARANGAY, ADDRESS, GENDER, MARITAL_STATUS, DATE_OF_BIRTH[, PLACE_OF_BIRTH, EMAIL, TELEPHONE_NUMBER, RELIGION, JOB, HAS_PENSION, TYPE, AMOUNT FROM person JOIN name ON person.PERSON_ID = name.PERSON_ID JOIN transaction_type ON person.PERSON_ID = transaction_type.PERSON_ID JOIN gender ON person.PERSON_ID = gender.PERSON_ID JOIN marital_status ON person.PERSON_ID = marital_status.PERSON_ID JOIN applicant ON person.PERSON_ID = applicant.APPLICANT_ID JOIN user_account ON person.PERSON_ID = user_account.PERSON_ID JOIN telephone ON person.PERSON_ID = telephone.PERSON_ID JOIN religion ON person.PERSON_ID = religion.PERSON_ID JOIN job ON person.PERSON_ID = job.PERSON_ID JOIN pension ON person.PERSON_ID = pension.PERSON_ID JOIN person_address ON person.PERSON_ID = person_address.PERSON_ID JOIN address ON person_address.ADDRESS_ID = address.ADDRESS_ID WHERE USERNAME = 'SC-358683' AND APPLICANT_TYPE = 'Senior Citizen';

SELECT CITIZEN_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, GENDER, JOB, MARITAL_STATUS, RELIGION, CONCAT(ADDRESS, ', ', BARANGAY) ADDRESS, TELEPHONE_NUMBER, HAS_PENSION, TYPE PENSION_TYPE, AMOUNT
FROM 
	APPLICANT AP, 
	PERSON PE, 
	NAME NA, 
	PERSON_ADDRESS PA, 
	ADDRESS AD, 
	JOB JO, 
	MARITAL_STATUS MS, 
	GENDER GE, 
	PENSION PS, 
	TELEPHONE TE,
	RELIGION RG
WHERE AP.APPLICANT_ID = PE.PERSON_ID
AND NA.PERSON_ID = PE.PERSON_ID AND NA.IS_DELETED = 'N'
AND PA.PERSON_ID = PE.PERSON_ID
AND PA.ADDRESS_ID = AD.ADDRESS_ID AND AD.IS_DELETED = 'N'
AND JO.PERSON_ID = PE.PERSON_ID AND JO.IS_DELETED = 'N'
AND MS.PERSON_ID = PE.PERSON_ID AND MS.IS_DELETED = 'N'
AND GE.PERSON_ID = PE.PERSON_ID AND GE.IS_DELETED = 'N'
AND PS.PERSON_ID = PE.PERSON_ID AND PS.IS_DELETED = 'N'
AND TE.PERSON_ID = PE.PERSON_ID AND TE.IS_DELETED = 'N'
AND RG.PERSON_ID = PE.PERSON_ID AND RG.IS_DELETED = 'N'
